### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by chrisguttandin** [feross/unmute-ios-audio#2]
Hi Feross,

would you be interested in adding TypeScript support? I would be happy to create a pull request with a .dts file in case you are. Just let me know.

**Comment by feross** [comment]
Sure. We can add types here. I would appreciate your help in keeping them up-to-date in case this module's API changes.

**Comment by chrisguttandin** [comment]
Yes, I'm using the package with TypeScript. So I should notice it in case something breaks.

**Comment by feross** [comment]
Thanks! I'll add you as a collaborator so you can participate more easily.
