### ISSUE TITLE
Correct CSP Rules

### ISSUE THREAD

**Issue by dlymann** [feross/unmute-ios-audio#7]
Hi,

I would like to understand exactly what CSP rule is required for the mute to work. Unfortunately no error is logged if the CSP rule does not apply. Therefore we have to set `default-src data:;` which is not optimal.

Thanks for implementing and maintaining unmute-ios-audio!

Best,
Daniel

**Comment by chrisguttandin** [comment]
Hi Daniel, you could make the CSP rule a bit more specific by using `media-src data:` instead. But as far as I know It's not possible to use a hash for data URLs.

**Comment by dlymann** [comment]
Thank you very much!
